import '../styles/globals.scss'
import '../styles/variables.scss'
import '../styles/dark.scss'
import Header from '@/components/header/Header'
import Nav from '@/components/nav/Nav'
import Content from '@/components/content/Content'
import DarkModeToggle from '@/components/darkModeToggle/DarkModeToggle'
import { vcrOsdMono } from '@/utils/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={vcrOsdMono.variable}>
      <body>
        <Header />
        <div className='wrapper'>
          <Nav />
          <Content>{children}</Content>
        </div>
        <DarkModeToggle />
      </body>
    </html>
  )
}
